### ISSUE TITLE
[Bug]: Wooden Buckets (mod) become Vanilla Buckets

### ISSUE THREAD

**Issue by pouchrat** [Mrbysco/MoreCauldrons#11]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

36.2.9

### Mod version

1.16.5-1.4.8

### Java version

Java 8

### Issue Description

When using a wooden bucket from [Wooden Buckets](https://www.curseforge.com/minecraft/mc-mods/wooden-buckets) to fill a More Cauldrons cauldron with water, the cauldron returns a metal (vanilla) bucket.

### Additional Information

![image](https://user-images.githubusercontent.com/38634418/163507426-8d8b9e5f-2ffe-44ae-9edb-25010ee4dc25.png)

![image](https://user-images.githubusercontent.com/38634418/163507451-bde24699-e24c-42f3-bcec-b784c503c1c6.png)

**Comment by Mrbysco** [comment]
This isn't an issue with More Cauldrons but an issue with the Wooden Buckets mod as the same behavior is also seen when a bucket from that mod is used with Ex Nihilo
