### ISSUE TITLE
Bug: Diamond/gold cauldrons craft into brick cauldrons.

### ISSUE THREAD

**Issue by Akitori** [Mrbysco/MoreCauldrons#2]
![2018-07-13_18 55 03](https://user-images.githubusercontent.com/24502131/42718430-6fbfa1a4-86ce-11e8-91c1-dec968377a53.png)

**Comment by Mrbysco** [comment]
Whoops... Will quickly fix.
Must've been tired when I made the recipes

**Comment by Mrbysco** [comment]
Update is live on curse
