### ISSUE TITLE
Don't use capitals in your package name >_<

### ISSUE THREAD

**Issue by Darkhax** [Mrbysco/MoreCauldrons#3]
Using upper case characters in your package name is bad practice, and can break how some systems interpret your classes.

**Comment by Mrbysco** [comment]
Didnt know that. Will change it for all of my mods when I get the chance to.
Ofcourse github won't notice the namechanges

**Comment by Mrbysco** [comment]
Changed to lowercase in https://github.com/Mrbysco/MoreCauldrons/commit/5ae5203c228e89a457943f50075dc10f64ba845a

**Comment by Darkhax** [comment]
Thanks :P

**Comment by Mrbysco** [comment]
It's a left-over from when I dove into modding without knowing how to mod. I didn't know I had to keep package names lowercase. And since I didn't know I kept doing it :P, But yeah. I will change it whenever I have to release a new update for any of my mods.
