### ISSUE TITLE
support for other mods

### ISSUE THREAD

**Issue by Mrthomas20121** [Mrbysco/MoreCauldrons#4]
Add support for others mod that add _woods_ or _stones_(like thaumcraft greatwood, natura wood, chisel stones, twilight forest woods just to name a few).

i can even help with the textures :)

**Comment by MokahTGS** [comment]
I'd settle for support for pipes...why these don't just work like Crucibles from ExNihilo is beyond me.

**Comment by snowyleopardcc** [comment]
Good morning / afternoon / evening.

I have been messing around for nearly the last 2 hours in game trying to get fluid extraction working.  Ender I/O and Thermal fluiducts are not compatible,  however for some reason XNET is.

After looking over the code,  it appears there is no forge fluid capabilities at all,  unless I am blind and over looked them.

Are there plans to add such fluid handlers in within the near future so as to add compatibility from other mods fluid handlers?

**Comment by Mrbysco** [comment]
By default they act like vanilla cauldrons. When Inspirations is installed they mimic whatever Inspirations does. Meaning if you want proper fluid extraction you should test if fluid extraction works properly with only Inspirations installed.
If it does I have done something wrong on my part.

**Comment by snowyleopardcc** [comment]
Okay,  well now.  So I have a clean copy of our community pack with just `Inspirations` installed (ver -0.2.9) ,  pulled out `More Cauldrons`.  Still the same deal.  Cannot even insert fluids via ducts as seen below.


![2020-04-11_07 55 02](https://user-images.githubusercontent.com/14970681/79044355-3f125e00-7bca-11ea-936e-ce9c06c8a609.png)

**Comment by snowyleopardcc** [comment]
I'm having to seriously reconsider if we're trying to do something with the mod that was not intended or not.  We originally installed `More Cauldrons` for better custom recipe handling.  However automation does not seem possible at this point.

**Comment by Mrbysco** [comment]
I can't fix the automation as that's something that isn't up to me. All I do is extend Inspirations.

I'll see what I can do about the mod support for blocks

**Comment by snowyleopardcc** [comment]
It's fine.  I'm writing a mod now as we speak that has automatable cauldrons.  No worries,  I understand what you are doing now.

Thanks!
CC

**Comment by Mrbysco** [comment]
A quote from a conversation I had with @KnightMiner when I asked him about the fluid handling: 
"I've discussed this a few times, the cauldron requires increments of 250 mb, it's not a real fluid tank
So if your pipe does not support that speed it won't work
It's part of the reason for my feature for dispensers to fill cauldrons"

**Comment by KnightMiner** [comment]
Yeah, I wanted to add proper fluid handling for cauldrons, but the 1.12 version is not a true fluid tank, it holds 3 bottles, or 4 with bigger cauldrons enabled, and a fluid type. However, bottles do not translate well to milibuckets, hence the large increment.

For more details on the in mod solution, Inspirations allows you to use whitelisted fluid containers to fill and empty both the cauldron and modded tanks, so anything you can pull fluids from using pipes, you can also do so using a bucket in a dispenser.

----

I am working on a better way to handle this for 1.14 without breaking vanilla assumptions about cauldrons, but I have no plans to change the 1.12 version.
