### ISSUE TITLE
Wooden cauldrons causing fires when filled with blood

### ISSUE THREAD

**Issue by Gunner76th** [Mrbysco/MoreCauldrons#5]
Minecraft: 1.12.2
Forge: 2831
Mod Pack: Sky Factory 4 version 4.0.5
More Cauldrons: More-Cauldrons-1.4.3.jar

Issue: While using the wooden cauldrons certain fluids which do not have a heat value are causing fires to be spawned. 

Expected behavior: When filled with a fluid that does not have a heat value, the cauldron should treat the fluid the same as water and not spawn fires. 

Steps to reproduce: Using the above versions listed above, or using the above listed modpack, do the following: 

Place a wooden cauldron on the ground with no blocks beside it. 
![image](https://user-images.githubusercontent.com/5566872/58387381-adaef300-7fdb-11e9-8a79-2bd04f91f5d1.png)

Take a single bucket of blood and dump it into the cauldron. 
![image](https://user-images.githubusercontent.com/5566872/58387374-9b34b980-7fdb-11e9-81d4-8f372cf088d3.png)

Wait a few moments, and then observe fires spawning around the cauldron. 
![image](https://user-images.githubusercontent.com/5566872/58387361-5dd02c00-7fdb-11e9-902b-b2f6fc65091d.png)

Summary: Blood is a fluid that inherently is not a "hot" fluid. When poured in the world, it behaves exactly the same as water, even to the point of turning lava into obsidian. When poured into a wooden cauldron however, fires are spawned as if lava was placed in the cauldron.

**Comment by Mrbysco** [comment]
Since when is blood's temperature higher than lava...

**Comment by Gunner76th** [comment]
That is my point, it isn't supposed to be. And yet when placed in the world, it acts like water, not a hot fluid.

**Comment by Gunner76th** [comment]
This is confirmed to happen with only the following mods installed:
Mantle 1.12-1.3.3.55
Tinkers Construct 1.12.2-2.12.0.135
More Cauldrons 1.4.3
Inspirations 1.12.2-0.2.4

All configs used are default, unedited config files. I have confirmed this issue exists by recreating it in a new single player world using only the mods listed above.

**Comment by sam-kirby** [comment]
If I'm reading this correctly, you're looking for a temperature of 350K, at which point wood becomes flammable - this is about 75℃... (https://github.com/Mrbysco/MoreCauldrons/blob/master/src/main/java/com/Mrbysco/MoreCauldrons/events/EnhancedRecipeEvents.java#L80)

Lava has a temperature of 1300K (https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fluids/FluidRegistry.java#L80-L85)

Blood has a temperature of 420K - a fair way above boiling, but not as hot as lava. (https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/shared/TinkerFluids.java#L185)

Wood has an ignition temperature of ~350℃ or ~625K (https://www.iafss.org/publications/aofst/1/380/view/aofst_1-380.pdf)

Edit to add that inspirations harms entities and sets them on fire if they're in a cauldron with a fluid temperature over 450K (https://github.com/KnightMiner/Inspirations/blob/master/src/main/java/knightminer/inspirations/recipes/tileentity/TileCauldron.java#L350)

**Comment by sam-kirby** [comment]
I have confirmed that the above is the issue. Blood is a little on the hot side, but more importantly the cauldron is igniting at a very low temperature. A test build with the threshold set to 450 did not cause the cauldron to ignite when blood was inside it, though lava still caused fires. Further, by adding additional debugging output, I confirmed that the above temperatures (Blood 420K, Lava 1300K) are accurate and have not been modified in SF4.

450K seems a sensible threshold as this is also the point at which Inspirations will cause entities standing in the cauldron to catch fire.

**Comment by Gunner76th** [comment]
Ok, so explain why, based off of the evidence you posted above, blood which has a temp of 420K is causing fires in a cauldron which only does so when the fluid inside it is over 450K? The blood is 30K below the set point and thus should not be causing ignition. 

So is this an issue with inspirations, tinkers, or More cauldrons? Blood is not a flammable substance, nor one with anywhere near enough heat to cause fire (otherwise the players should always be on fire since blood is within them). When poured in the world you can swim in blood the same as water taking no damage until you run out of air. Based off of the mod code information posted above between inspirations and tcon, it looks like this is a bug with inspirations causing fires from a fluid which is 

Also, which I like that you did give reference material for the ignition temperature of wood, citing things from the real world to prove mechanics within minecraft is pointless as the 2 are generally not related at all. Yes some mods do try to emulate real world values for most items, however the majority of things do not. What would be helpful and relevant instead would be to see the code for MC specifically that sets the ignition temperature of wood.

**Comment by sam-kirby** [comment]
The very first paragraph of my first comment

> If I'm reading this correctly, you're looking for a temperature of 350K, at which point wood becomes flammable - this is about 75℃... (https://github.com/Mrbysco/MoreCauldrons/blob/master/src/main/java/com/Mrbysco/MoreCauldrons/events/EnhancedRecipeEvents.java#L80)

In case this isn't clear to you, More Cauldrons wooden cauldrons will ignite at 350K at present, which is less than 420K.

This is mostly an issue with More Cauldrons, though Tinkers' could definitely make blood a little cooler. Though that may make it too much in line with the real world for you...

I included a reference to IRL research as a first pass at finding a suitable value for the ignition temperature. If you read my comment, you'll see I settled on 450K using sources from another mod.

In Vanilla Minecraft, fluids have no concept of temperature. This is a compatibility feature added by Forge so that mods can gain an understanding of how a fluid is supposed to behave. Wood does not have an ignition temperature. It is simply tagged as a flammable block.

**Comment by Gunner76th** [comment]
Ok sorry for the misunderstanding. And it's not that it would be too much in line with real world values, it has just been my experience that anytime you try to expect things in game to follow real world values or mechanics, they never seem to. 

As for the results of the research, yes it does look like @Mrbysco is setting the ignition temperature a bit too low, The current setpoint of 350K, 75C is the equivalent to 167F which is less than the heat required to even boil water or ignite books. Changing the value upwards towards 450K or even 625K would not only bring the mod more inline with other mods, but also make this more realistic.

**Comment by Mrbysco** [comment]
To work around I've uploaded a new build of More Cauldrons that upped the minimal temperature required to burn wooden cauldrons to 450K or higher

**Comment by bonii-xx** [comment]
Just as a (late) followup: Bloods temperature will be reduced, I don't think it was ever intended to be that hot. Probably copy'n'paste
