### ISSUE TITLE
I can't insert boulders to turn into lava, even with torch / lava below and Inspirations Mod installed.

### ISSUE THREAD

**Issue by CapivaraTupiniquim** [Mrbysco/MoreCauldrons#6]
1.12.2

**Comment by Mrbysco** [comment]
Are you running a modpack? If so which?
If not: Getting lava from stone is not a feature of MoreCauldrons. MoreCauldrons only adds more cauldrons. In SkyFactory it was done using CraftTweaker and Inspirations.

**Comment by CapivaraTupiniquim** [comment]
@Mrbysco I see, I use it in a custom modpack and it already has inspirations. Can you help me use Craft Tweaker to generate the lava?

**Comment by Mrbysco** [comment]
I can't help you with that but I can link you to SkyFactory's page so you can find how they do it.
https://github.com/DarkPacks/SkyFactory-4/tree/master/src/scripts/crafttweaker

**Comment by CapivaraTupiniquim** [comment]
Obrigado!
