### ISSUE TITLE
ceramic buckets again

### ISSUE THREAD

**Issue by benbenlaw** [Mrbysco/MoreCauldrons#8]
## Client Info
* Minecraft Version: 1.16.4

* Forge Version: latest
* Mod Version:  latest
* Java Version:  latest

**Comment by benbenlaw** [comment]
https://github.com/KnightMiner/Ceramics/issues/68

**Comment by Mrbysco** [comment]
I'll revert my changes and look at it another time as atm I am clueless how to fix the issue

**Comment by benbenlaw** [comment]
yeah thats ok i will stick to the version i am on becuase im using ceramics to get water in vaurdrens in my modpack thanks for getting back to me

**Comment by Mrbysco** [comment]
A new version has been uploaded that should fix the issue
